# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/CaravelFPGA/Caravel_FPGA_2025/CARAVEL/CARAVEL.srcs/sources_1/ip/bram/bram.xci
# IP: The module: 'bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/CaravelFPGA/Caravel_FPGA_2025/CARAVEL/CARAVEL.srcs/sources_1/ip/bram/bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/CaravelFPGA/Caravel_FPGA_2025/CARAVEL/CARAVEL.srcs/sources_1/ip/bram/bram.xci
# IP: The module: 'bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/CaravelFPGA/Caravel_FPGA_2025/CARAVEL/CARAVEL.srcs/sources_1/ip/bram/bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
