# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.srcs/sources_1/ip/clk_fix_1/clk_fix.xci
# IP: The module: 'clk_fix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.gen/sources_1/ip/clk_fix_1/clk_fix_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_fix'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.gen/sources_1/ip/clk_fix_1/clk_fix.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.gen/sources_1/ip/clk_fix_1/clk_fix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.srcs/sources_1/ip/clk_fix_1/clk_fix.xci
# IP: The module: 'clk_fix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.gen/sources_1/ip/clk_fix_1/clk_fix_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.gen/sources_1/ip/clk_fix_1/clk_fix.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Caravel_NPU_FPGA_2025/CARAVEL/CARAVEL.gen/sources_1/ip/clk_fix_1/clk_fix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
